Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/10/2023
Var
N, I, R : inteiro
inicio
Escreva("Digite um numero")
leia(N)
I<- 1
enquanto (I <= 10) faca
R <- N * I
escreval( N, " X ", I, " = ", R)
I<-(I + 1)
fimenquanto
Fimalgoritmo