Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/10/2023
var
Y, sobra : inteiro
inicio
Y <- 0
enquanto (Y <= 20) faca
sobra<- Y - 2 * (Y div 2)
se (sobra <> 0) entao
escreval(Y)
fimse
Y<-(Y + 1)
fimenquanto
Fimalgoritmo