Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/10/2023
var
P,I,B,z:inteiro
inicio
Escreval("Escreva o numero, e a potência desejada")
leia (B,z)
P<- 1
I<- 1
enquanto (I <= z) faca
P<- P * B
I<- I + 1
fimenquanto
escreva(P)
Fimalgoritmo