Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/10/2023
Var
// Seção de Declarações das variáveis 
C, F : real
inicio
C<- 10
escreval("Celsius/Fahrenheit")
enquanto (C <= 100) faca
F<-(9 * C + 160) / 5
escreval(C, F)
C<-(C + 10)
fimenquanto
Fimalgoritmo