Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/10/2023
var
I, N, SOMA : inteiro
MEDIA : real
inicio
SOMA<- 0
I<- 1
Escreval("Digite 10 numeros")
enquanto (I <= 10) faca
leia(N)
SOMA<-SOMA + N
I<- I + 1
fimenquanto
MEDIA<- SOMA / 10
escreval( SOMA, MEDIA)

Fimalgoritmo