Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2023
var
numero, quadrado: inteiro

inicio
para numero de 15 ate 200 faca
quadrado <- numero * numero
escreval("O quadrado de ", numero, " é ", quadrado)
fimpara

Fimalgoritmo