Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2023
var
soma, contador: inteiro

inicio
soma <- 0
para contador de 1 ate 100 faca
soma <- soma + contador
fimpara
escreval("O total da soma dos primeiros cem números é: ", soma)
Fimalgoritmo