Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2023
var
   soma, numero: inteiro

inicio
soma <- 0
para numero de 1 ate 500 faca
se numero % 2 = 0 entao
soma <- soma + numero
fimse
fimpara
escreval("A soma dos valores pares de 1 até 500 é: ", soma)

Fimalgoritmo