Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2023
var
   base, resultado: inteiro
   expoente: inteiro

inicio
base <- 3
resultado <- 1
para expoente de 0 ate 15 faca
escreva(base, "^", expoente, " = ", resultado)
escreval("")
resultado <- resultado * base
fimpara
Fimalgoritmo