Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/10/2023
Var
   numero, quadrado: Inteiro

Inicio
Para numero de 15 ate 200 faca
quadrado <- numero * numero
Escreval("O quadrado de ", numero, " é ", quadrado)
FimPara



Fimalgoritmo