Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/10/2023
Var
quadro, totalGraos: Inteiro

Inicio
totalGraos <- 0

Para quadro de 1 ate 64 faca
totalGraos <- totalGraos + quadro
FimPara
Escreval("O número total de grãos de trigo no tabuleiro é: ", totalGraos)
FimAlgoritmo